"""init extension

Revision ID: 20250219193149
Revises:
Create Date: 2025-02-19 19:31:49.060898

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "20250219193149"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
